### ISSUE TITLE
Error while running the default pear terminal app

### ISSUE THREAD

**Issue by ShivankChopra** [holepunchto/pear#333]
Hi! I tried to make and run a simple terminal app using pear cli, seems to give errors cannot find module. No code was modified, just initialized a new project using `pear init --yes --type terminal`. I did install npm modules after initializing project. 

Got following error log running the project by executing `pear run -d .` inside initialized folder:

```
x Cannot find module './-app/-app/dev'
x Error: Unknown [ code: MODULE_NOT_FOUND ] Error: Cannot find module './-app/-app/dev'
    at DependencyStream._resolveModule (file:///C:/Users/Shivank%20Chopra/AppData/Roaming/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/node_modules/dependency-stream/index.js:124:17)
    at async DependencyStream._open (file:///C:/Users/Shivank%20Chopra/AppData/Roaming/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/node_modules/dependency-stream/index.js:47:19)
```

I checked the boot.bundle (in `%appdata%/pear\by-dkey\7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28\1`) file, 
the error seems to come while determining import and require modules.

![image](https://github.com/user-attachments/assets/78fec334-7ea1-4ab2-97fb-c8f6b7784396)

This was tested on both windows 11 and Mac systems, getting same error in terminal app.

Cant seem to pinpoint reason! :/

**Comment by rafapaezbas** [comment]
@ShivankChopra thank you for you report. I cannot reproduce the issue on my Windows machine, could you try with latest platform release? If the issue persists please let us know.
