### ISSUE TITLE
Pear do not work anymore in my Windows shell

### ISSUE THREAD

**Issue by parkitoapp** [holepunchto/pear#337]
I installed Pear on Windows 11 with the documented installation process:

1. npm i -g pear
2. run 'pear' on the command line
3. And after I launch the command `pear run pear://keet` and it works.

After this I follow this tutorial: [Connect two peers.](https://docs.pears.com/how-tos/connect-two-peers-by-key-with-hyperdht). 

I launched this command: `pear dev` on the /server-app folder and it works properly 😉
By this moment I tried some commands of the pear CLI (like help, run, ecc...) to familiarize with it but without fully understand what i was doing. And after I close and open Visual Studio Code.

**Now any Pear command a paste on the shell doesn't work anymore.
Now this is the log if I launch the command `pear` on my windows powershell:**

`PS C:\Users\Andrea\Desktop\Dev\pears\con-peers2> pear
2024-10-04T09:01:01.855Z cli exiting due to unhandled rejection
key=pqbzjhqyonxprx8...
length=4444
fork=0
platform=win32
arch=x64
pid=2452
uptime=30.018s
stack=Error: Could not connect in time
    at PearIPC._connect (file:///C:/Users/Andrea/AppData/Roaming/pear/by-dkey/7216eeac5c8..../1/boot.bundle/node_modules/pear-ipc/index.js:222:27)
    at async PearIPC._open (file:///C:/Users/Andrea/AppData/Roaming/pear/by-dkey/7216eeac5c879a2ca1dcff14bb..../1/boot.bundle/node_modules/pear-ipc/index.js:77:26)
    at async open (file:///C:/Users/Andrea/AppData/Roaming/pear/by-dkey/7216eeac5c879a2ca1..../1/boot.bundle/node_modules/ready-resource/index.js:37:5)

Error logged at C:\Users\Andrea\AppData\Roaming\pear\by-dkey\7216eeac5c879a2ca......\1\cli.crash.log`

This is the log file

`2024-10-04T08:42:34.590Z cli exiting due to unhandled rejection
key=pqbzjhqyonxprx8hghxexnmctw....
length=4444
fork=0
platform=win32
arch=x64
pid=11004
uptime=30.021s
stack=Error: Could not connect in time
    at PearIPC._connect (file:///C:/Users/Andrea/AppData/Roaming/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad4..../1/boot.bundle/node_modules/pear-ipc/index.js:222:27)
    at async PearIPC._open (file:///C:/Users/Andrea/AppData/Roaming/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c...../1/boot.bundle/node_modules/pear-ipc/index.js:77:26)
    at async open (file:///C:/Users/Andrea/AppData/Roaming/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d1..../1/boot.bundle/node_modules/ready-resource/index.js:37:5)
`

Now i try to uninstall Pear and re-install it. Also I ask you if there is a way to easily uninstall it.
My Best, ANdrea.

**Comment by CastenettoA** [comment]
I temporarily fixed it by uninstalling pear and reinstalling it on my Windows machine. My best, Andrea.

**Comment by parkitoapp** [comment]
Hi there, 
after reinstall pear on my pc (windows env) I followed this steps and sadly I see a similar error again:

The step i follow to get the error:
  1. Install pear on my pc (all ok. The `pear` command runs well on the shell).
  2. Init a new project following **Connect Two Peers** tutorial on docs.pears.com.
  3. Start the server file with `pear dev` ---> get no response from the shell ...
  4. Insert simple the command 'pear' on my shell and get back this error:

The error log:
`key=pqbz.......mntfyaddqy
length=4444
fork=0
platform=win32
arch=x64
pid=17776
uptime=30.018s
stack=Error: Could not connect in time
    at PearIPC._connect (file:///C:/Users/.../AppData/Roaming/pear/by-dkey/7216eeac.....8bd3b28/1/boot.bundle/node_modules/pear-ipc/index.js:222:27)
    at async PearIPC._open (file:///C:/Users/.../AppData/Roaming/pear/by-dkey/7216....d3b28/1/boot.bundle/node_modules/pear-ipc/index.js:77:26)
    at async open (file:///C:/Users/..../AppData/Roaming/pear/by-dkey/7216ee.....ea8bd3b28/1/boot.bundle/node_modules/ready-resource/index.js:37:5)

Error logged at C:\Users\....\AppData\Roaming\pear\by-dkey\7216eeac5c....d354ea8bd3b28\1\cli.crash.log`


This is my cli.crash.log

2024-10-11T09:59:27.596Z cli exiting due to unhandled rejection
key=pqb.....ntfyaddqy
length=4444
fork=0
platform=win32
arch=x64
pid=17776
uptime=30.018s
stack=Error: Could not connect in time
    at PearIPC._connect (file:///C:/Users/..../AppData/Roaming/pear/by-dkey/7216eeac5c879a2ca1dcff....354ea8bd3b28/1/boot.bundle/node_modules/pear-ipc/index.js:222:27)
    at async PearIPC._open (file:///C:/Users/..../AppData/Roaming/pear/by-dkey/7216eeac5c879a2c....bd3b28/1/boot.bundle/node_modules/pear-ipc/index.js:77:26)
    at async open (file:///C:/Users/.../AppData/Roaming/pear/by-dkey/7216....6d354ea8bd3b28/1/boot.bundle/node_modules/ready-resource/index.js:37:5)

My best

**Comment by CastenettoA** [comment]
Hi there,
after reinstall pear on my pc (windows env) I followed this steps and sadly I see a similar error again:

The step i follow to get the error:

Install pear on my pc (all ok. The pear command runs well on the shell).
Init a new project following Connect Two Peers tutorial on docs.pears.com.
Start the server file with pear dev ---> get no response from the shell ...
Insert simple the command 'pear' on my shell and get back this error:
The error log:
`key=pqbz.......mntfyaddqy
length=4444
fork=0
platform=win32
arch=x64
pid=17776
uptime=30.018s
stack=Error: Could not connect in time
at PearIPC._connect (file:///C:/Users/.../AppData/Roaming/pear/by-dkey/7216eeac.....8bd3b28/1/boot.bundle/node_modules/pear-ipc/index.js:222:27)
at async PearIPC._open (file:///C:/Users/.../AppData/Roaming/pear/by-dkey/7216....d3b28/1/boot.bundle/node_modules/pear-ipc/index.js:77:26)
at async open (file:///C:/Users/..../AppData/Roaming/pear/by-dkey/7216ee.....ea8bd3b28/1/boot.bundle/node_modules/ready-resource/index.js:37:5)

Error logged at C:\Users....\AppData\Roaming\pear\by-dkey\7216eeac5c....d354ea8bd3b28\1\cli.crash.log`

This is my cli.crash.log

2024-10-11T09:59:27.596Z cli exiting due to unhandled rejection
key=pqb.....ntfyaddqy
length=4444
fork=0
platform=win32
arch=x64
pid=17776
uptime=30.018s
stack=Error: Could not connect in time
at PearIPC._connect (file:///C:/Users/..../AppData/Roaming/pear/by-dkey/7216eeac5c879a2ca1dcff....354ea8bd3b28/1/boot.bundle/node_modules/pear-ipc/index.js:222:27)
at async PearIPC._open (file:///C:/Users/..../AppData/Roaming/pear/by-dkey/7216eeac5c879a2c....bd3b28/1/boot.bundle/node_modules/pear-ipc/index.js:77:26)
at async open (file:///C:/Users/.../AppData/Roaming/pear/by-dkey/7216....6d354ea8bd3b28/1/boot.bundle/node_modules/ready-resource/index.js:37:5)

My best

**Comment by CastenettoA** [comment]
Also, if I restart my pc the pear cli seems working, but after few shell command (eg. 1. pear info, 2. try to open pear://pq....1zmntfyaddqy with chrome, 3. pear help info) i get the same error `Could not connect in time at PearIPC._connect, /pear-ipc/index.js:222:27` when digiting simply `pear help info` on the windows powershell.

**Comment by rafapaezbas** [comment]
It is possible that the sidecar process of the platform was running as a zombie. Please try again with latest platform release (Length 5114) and let us know if it works for you know.

Also if you still see this behavior it would be useful if you could check if there are any `pear-runtime` processes running in the background. Latest release has improved the closing of zombie sidecar processes.
