### ISSUE TITLE
Invalid Hypercore key error on install

### ISSUE THREAD

**Issue by fpolli** [holepunchto/pear#512]
Following the Getting Started guide, I tried to install Pear on my 2023 M3 MacBook Pro using npm. Below is the result:

```
zsh prompt% npm i -g pear
added 101 packages in 7s
zsh prompt% pear
Installing Pear Runtime (Please stand by, this might take a bit...)

Pear Runtime installed!

Finish the installation by opening the runtime app

pear run pear://runtime

Or by adding the following to your path

export PATH="/my/super/secret/path/pear/bin:$PATH"
zsh prompt% pear run pear:://runtime
Warning! To complete the Pear-Runtime installation, add the following to the beginning of your $PATH:
/my/super/secret/path/pear/bin
Until then, this request will be forwarded to the internal PEAR binary for you.
✖ Error: Invalid Hypercore key
    at decode (file:///my/super/secret/path/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/node_modules/hypercore-id-encoding/index.js:30:9)
    at parse (file:///my/super/secret/path/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/node_modules/pear-link/index.js:45:39)
    at run (file:///my/super/secret/path/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/run.js:24:31)
    at Command.run [as _runner] (file:///my/super/secret/path/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/cmd/run.js:23:47)
    at runAsync (file:///my/super/secret/path/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/node_modules/paparam/index.js:727:13)
    at Command.parse (file:///my/super/secret/path/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/node_modules/paparam/index.js:228:26)
    at module.exports (file:///my/super/secret/path/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/cmd/index.js:244:23)
    at async cli (file:///my/super/secret/path/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/cli.js:18:3)
✖ Error: Unknown [ code: (none) ] Error: Invalid Hypercore key
    at decode (file:///my/super/secret/path/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/node_modules/hypercore-id-encoding/index.js:30:9)
    at parse (file:///my/super/secret/path/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/node_modules/pear-link/index.js:45:39)
    at run (file:///my/super/secret/path/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/run.js:24:31)
    at Command.run [as _runner] (file:///my/super/secret/path/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/cmd/run.js:23:47)
    at runAsync (file:///my/super/secret/path/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/node_modules/paparam/index.js:727:13)
    at Command.parse (file:///my/super/secret/path/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/node_modules/paparam/index.js:228:26)
    at module.exports (file:///my/super/secret/path/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/cmd/index.js:244:23)
    at async cli (file:///my/super/secret/path/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/boot.bundle/cli.js:18:3)
```

**Comment by mafintosh** [comment]
you added two colons in pear, ie it should be pear://runtime

**Comment by fpolli** [comment]
Absolutely right. Thanks!
