### ISSUE TITLE
windows 10, terminal not working.

### ISSUE THREAD

**Issue by Lightnet** [holepunchto/pear#99]
Did try the desktop and fail to load html. Did try the terminal and it launch desktop and not terminal.

Windows 10 64bit nodejs 20.11.1

pear 1.0.2

```
024-03-22T21:56:33.258Z cli exiting due to unhandled rejection
key=pqbzjhqyonxprx8hghxexnmctw75mr91ewqw5dxe1zmntfyaddqy
length=2757
fork=0
platform=win32
arch=x64
pid=21496
uptime=20.106s
stack=Error: Could not connect in time
    at bootpipe (file:///C:/Users/<>/AppData/Roaming/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/2/boot.bundle/lib/connect.js:43:25)
    at async cli (file:///C:/Users/<>/AppData/Roaming/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/2/boot.bundle/cli.js:11:19)

```

**Comment by davidmarkclements** [comment]
should work now
